server:
  port: 9080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/student
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    application:
      version: 1.0
path:
  upload: F://img//

logging:
  file: /e:/sy8Manage.log
  level:
    root: info
    com.cn: debug


#接口apiDoc文档的说明字段
doc:
  api:
    basePath: /
    version: ${spring.application.version}
    contact: 商户测试
    termsOfServiceUrl:
    license: 商业授权协议
    licenseUrl: http://www.sy8.com